name: Build Nix

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-tray:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: lgtv-tray-remote
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build lgtv-tray
        run: nix build .#default --print-build-logs
        working-directory: lgtv-tray

  build-plasmoid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: lgtv-tray-remote
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build plasmoid
        run: nix build .#default --print-build-logs
        working-directory: plasmoid
